# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

filegroup(
    name = "service",
    srcs = [
        "compiler_gym-cgra-service",
        "cgra_service.py",
        "cgra_env.py",
    ],
    visibility = ["//visibility:public"],
)